config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :contacts

  mount API => '/'

  resources :contacts
  resources :pets
 
  resources :conversations do
    resources :messages
  end

  root 'application#dashboard'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  geocoded_by :full_street_address
  after_validation :geocode
  has_many :pets
  acts_as_messageable

  has_attached_file :profile_image, styles: { thumb: '100x100>' }
  validates_attachment_content_type :profile_image, content_type: %r{\Aimage/.*\z}

  def full_street_address
    "#{street_number} #{street_name} #{suburb} #{post_code}"
  end

  def name
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(_object)
    nil
  end
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  belongs_to :contact
  has_many :pictures
  enum gender: %i[male female]

  def age
    "#{years} years #{months} months" if years && months
  end
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  belongs_to :pet

  has_attached_file :image, styles: { thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :authenticate_contact!

  skip_before_action :authenticate_contact!, only: [:dashboard]

  def dashboard
    @nearby_contacts = if current_contact
                         Contact.near(
                          [current_contact.latitude || SYDNEY_LATITUDE, current_contact.longitude || SYDNEY_LONGITUDE], 10)
                       else
                         Contact.near([SYDNEY_LATITUDE, SYDNEY_LONGITUDE], 10)
                       end
                       .limit(100)
                       .map do |contact|
      { lat: contact.latitude, lng: contact.longitude, infowindow: info(contact) }
    end.to_json
  end

  private

  def info(contact)
    view_context.content_tag(:div, pet_link(contact))
  end

  def pet_link(contact)
    pet_picture = contact.pets.first&.pictures&.first
    path = contact_path(contact)
    if pet_picture
      image = pet_picture.image(:thumb)
      view_context.link_to(view_context.image_tag(image), path)
    else
      view_context.link_to(contact.name, path)
    end
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  layout "application"
  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find params[:id]
  end

  def edit
    @contact = Contact.find params[:id]
  end

  def update
    @contact = Contact.find params[:id]
    @contact.update params[:contact].permit!
  end

  def create
    Contact.create params[:contact].permit!
  end

  def index
    @contacts = Contact.near(
      [current_contact.latitude || SYDNEY_LATITUDE, current_contact.longitude || SYDNEY_LONGITUDE],
      50
    )
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  def index
    @conversations = current_contact.mailbox.conversations
  end

  def show
    @conversation = current_contact.mailbox.conversations.find(params[:id])
  end

  def create
    current_contact.send_message(Contact.find(params[:contact_id]), params[:body], params[:subject])
  end

  def new
    @contact_id = params[:contact_id]
  end
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  def new
    @pet = Pet.new
  end

  def show; end

  def edit; end

  def update; end

  def create
    pet = current_contact.pets.create pet_params
    pet.pictures.create pet_image_params
    redirect_to pets_path
  end

  def index
    @pets = if params[:contact_id]
              Contact.find(params[:contact_id]).pets
            else
              current_contact.pets
            end
  end

  def destroy
    Pet.destroy params[:id]
    redirect_to pets_path
  end

  private

  def pet_params
    params.required(:pet).permit(%i[name gender years months description])
  end

  def pet_image_params
    params.required(:pet).permit(:pictures)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

module ConversationsHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/pets_helper.rb
# frozen_string_literal: true

module PetsHelper
end

app/views/application/dashboard.html.haml
#contacts{ 'data-contacts' => @nearby_contacts } Near by doggies
#map-list{'style'=>'width: 800px; height: 400px;'}
  

app/views/contacts/edit.html.haml
.container
  = simple_form_for(@contact, html: { class: 'form' }) do |f|
    .row
      .form-group.col-6
        = f.input :first_name, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :last_name, input_html: { class: 'form-control' }
      .form-group.col-12
        = f.file_field :profile_image, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :unit, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :street_number, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :street_name, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :suburb, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :state, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :post_code, input_html: { class: 'form-control' }
    = f.button :submit, { class: 'btn-primary' }

app/views/contacts/index.html.haml
.container
  .row
    - @contacts.each do |contact|
      .col-4.mb-3
        %div.card{'style'=>"max-width: 18rem;"}
          .card-header
            = contact.first_name
          = image_tag contact.profile_image(:thumb), {class: "card-img-top"} if contact.profile_image.present?
          .card-body
            = mail_to contact.email
            %br
            = "#{contact.unit} #{contact.street_number} #{contact.street_name} #{contact.suburb} #{contact.post_code}"
            %br
            - if(contact == current_contact)
              = link_to 'new pet', new_pet_path
            - else
              = link_to 'message', new_conversation_path({contact_id: contact.id})

app/views/contacts/new.html.haml
.container
  = simple_form_for(@contact, html: { class: 'form' }) do |f|
    .row
      .form-group.col-6
        = f.input :first_name, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :last_name, input_html: { class: 'form-control' }
      .form-group.col-12
        = f.file_field :profile_image, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :unit, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :street_number, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :street_name, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :suburb, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :state, input_html: { class: 'form-control' }
      .form-group.col-6
        = f.input :post_code, input_html: { class: 'form-control' }
    = f.button :submit, { class: 'btn-primary' }

app/views/contacts/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/contacts/show.html.haml
.container
  #contact{'style'=>'width: 800px;', 'data' => {'lat' => @contact.latitude, 'long' => @contact.longitude }}
  .col-4.mb-3
    %div.card{'style'=>"max-width: 18rem;"}
      .card-header
        = @contact.first_name
      = image_tag @contact.profile_image(:thumb), {class: "card-img-top"} if @contact.profile_image.present?
      .card-body
        = mail_to @contact.email
        %br
        = "#{@contact.unit} #{@contact.street_number} #{@contact.street_name} #{@contact.suburb} #{@contact.post_code}"
        %br
        - if(@contact == current_contact)
          = link_to 'new pet', new_pet_path
        - else
          = link_to 'chat', new_conversation_path({contact_id: @contact.id})
  #pets
    - @contact.pets.each do |pet|
      %div
        = image_tag pet.pictures.first.image.url, size: "100x100" if pet.pictures.first.image.present?
        = pet.name
        = pet.gender
        = "#{pet.years} years #{pet.months} months"

app/views/conversations/index.html.haml
%h4 Inbox
.row.highlight
  %div.col-2
    Name
  %div.col-2
    Subject
  %div.col-4
    Message
  %div.col-3
    Received at
  
- @conversations.each do |conversation|
  - message = conversation.receipts_for(current_contact).last.message
  .row.highlight
    %div.col-2
      = link_to message.sender.name, contact_path(message.sender)
    %div.col-2
      = conversation.subject
    %div.col-4
      = message.body
    %div.col-3
      = message.created_at.strftime('%Y-%m-%d %H:%M')
    %div.col-1
      = link_to 'View', conversation_path(conversation)

app/views/conversations/new.html.haml
.row
  .col-12.col-md-6
    = simple_form_for(:conversation, url: '/api/conversations', html: {'data-type' => 'json', class: 'form', remote: true }) do |f|
      .form-group
        = hidden_field_tag 'contact_id', @contact_id
      .form-group
        = f.input :subject, input_html: { name: 'subject' ,class: 'form-control' }
      .form-group
        = f.input :reply,as: :text, input_html: { name: 'body',class: 'form-control' }
      .form-group.d-flex.justify-content-end
        = f.button :submit, "Send", { class: 'btn btn-primary' }

app/views/conversations/show.html.haml
%h3
  = @conversation.subject
.col-sm-8.col-sm-offset-4.frame
  %ul
    - @conversation.receipts_for(current_contact).order(created_at: :desc).each do |receipt|
      - date = receipt.message.created_at
      - text = receipt.message.body
      - if current_contact.id == receipt.message.sender.id
        %li{style: "width:100%"}
          .msj.macro
            .avatar{style: "width: 100%;"}
              - if receipt.message.sender.profile_image.present?
                = link_to contact_path(receipt.message.sender) do
                  = image_tag receipt.message.sender.profile_image(:thumb), {class: "img-circle", style: "width:100%;"}
              .text.text-l
                %p
                  = text
                %p
                  %small
                    = date
      - else
        %li{style: "width:100%;"}
          .msj-rta.macro
            .text.text-r
              %p
                = text
              %p
                %small
                  = date
            .avatar{style:"padding:0px 0px 0px 10px !important; width: 100%;"}
              - if receipt.message.sender.profile_image.present?
                = link_to contact_path(receipt.message.sender) do
                  = image_tag receipt.message.sender.profile_image(:thumb), {class: "img-circle", style: "width:100%;"}

  %div{style:"padding:5px;"}
    .msj-rta.macro
      = simple_form_for(:message, url: '/api/messages', html: { id: 'conversation-form', class: 'form', style: 'width: 100%;', remote: true }) do |f|
        = f.hidden_field :conversation_id, value: @conversation.id, name: "conversation_id"
        %div{style:"padding:10px;"}
          .text.text-r{style: "background:whitesmoke !important"}
            %input.mytext{placeholder:"Type a message", name: 'body', id: 'conversation-input', type:'text'}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yang</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyDSbM-MdpVSx6rVLJoed9bvggWNqm3grNU"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar justify-content-end">
        <%- if(current_contact) %>
          <%= link_to('Home', '/', { :class=>"nav-link" }) %>
          <%= link_to('Account', edit_contact_path(current_contact), { :class=>"nav-link" }) %>
          <%= link_to('Pets', pets_path,{ :class=>"nav-link" }) %>
          <%= link_to('Inbox', conversations_path, { :class=>"nav-link" }) %>
          <%= link_to('Contacts', contacts_path, { :class=>"nav-link" }) %>
          <%= link_to('Logout', destroy_contact_session_path, method: :delete, :class=>"nav-link" ) %>
        <%- else %>
          <%= link_to('Home', '/', { :class=>"nav-link" }) %>
          <%= link_to('Login', new_contact_session_path, { :class=>"nav-link" }) %>
          <%= link_to('Sign up', new_contact_registration_path, { :class=>"nav-link" }) %>
        <%- end %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/index.html.haml
.row
  - @pets.each do |pet|
    .col-4.mb-3
      %div.card{'style'=>"max-width: 18rem;"}
        .card-header
          .row
            .col-10
              = pet.name
            .col-2
              = link_to 'x', pet_path(pet.id), method: 'delete'
        = image_tag pet.pictures.first.image(:thumb) if pet.pictures.first && pet.pictures.first.image.present?
        .card-body
          = pet.gender
          %br
          = pet.age

- if params[:contact_id].nil?
  = link_to 'add', new_pet_path

app/views/pets/new.html.haml
= simple_form_for(@pet, html: { class: 'form' }) do |f|
  .form-group
    = f.input :name, input_html: { class: 'form-control' }
    = f.association :pictures do |pf|
      .form-group
        = pf.file_field :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :gender, :as => :select, :collection => [:male,:female], input_html: { class: 'form-control' }
  .form-group
    = f.input :years, input_html: { class: 'form-control' }
  .form-group
    = f.input :months, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }
  
  = f.button :submit, { class: 'btn-primary' }